import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Gaby',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
  ],

  products: [
    {
      name: "And Then There Were None",
      image: "/images/p1.jpg",
      author: "Agatha Christie",
      price: 7.99,
      countInStock: 10,
      rating: 4.5,
      description: "by Agatha Christie",
      genre: "fiction",
      release_date: new Date("<1939-11-06>"),
    },
    {
      name: "Alice's Adventures in Wonderland",
      image: "/images/p2.jpg",
      author: "Lewis Carroll",
      price: 10.0,
      countInStock: 20,
      rating: 4.0,
      description: "by Lewis Carroll",
      genre: "fantasy",
      release_date: new Date("<1865-01-01>"),
    },
    {
      name: "Harry Potter and the Goblet of Fire",
      image: "/images/p3.jpg",
      author: "J.K. Rowling, Mary GrandPre (Illustrator)",
      price: 11.69,
      countInStock: 10,
      rating: 4.8,
      description: "by J.K. Rowling, Mary GrandPre (Illustrator)",
      genre: "fantasy",
      release_date: new Date("<2005-11-18>"),
    },
    {
      name: "Anne of Green Gables",
      image: "/images/p4.jpg",
      author: "L.M. Montgomery",
      price: 7.99,
      countInStock: 15,
      rating: 4.5,
      description: "by L.M. Montgomery",
      genre: "autobiography",
      release_date: new Date("<1908-06-01>"),
    },
    {
      name: "Bridge to Terabithia",
      image: "/images/p5.jpg",
      author: "Katherine Paterson, Donna Diamond (Illustrator)",
      price: 7.99,
      countInStock: 5,
      rating: 4.5,
      description: "by Katherine Paterson, Donna Diamond (Illustrator).",
      genre: "fantasy",
      release_date: new Date("<2007-02-16>"),
    },
    {
      name: "Harry Potter and the Sorcerer's Stone",
      image: "/images/p6.jpg",
      author: "J.K. Rowling, Mary GrandPre (Illustrator)",
      price: 8.99,
      countInStock: 12,
      rating: 4.5,
      description: "A 1997 fantasy novel by British author J.K. Rowling.",
      genre: "fantasy",
      release_date: new Date("<1997-06-26>"),
    },
    {
      name: "The Great Gatsby",
      image: "/images/p7.jpg",
      author: "F. Scott Fitsgerald",
      price: 8.69,
      countInStock: 14,
      rating: 4.7,
      description: "1925 novel by American writer F. Scott Fitzgerald.",
      genre: "tragedy",
      release_date: new Date("<1925-04-10>"),
    },
    {
      name: "To Kill A Mockingbird",
      image: "/images/p8.jpg",
      author: "Harper Lee",
      price: 9.49,
      countInStock: 9,
      rating: 4.4,
      description: "1960 novel by American author Harper Lee.",
      genre: "Southern Gothic",
      release_date: new Date("<1960-7-11>"),
    },
    {
      name: "Brave New World",
      image: "/images/p9.jpg",
      author: "Aldous Huxley",
      price: 7.69,
      countInStock: 5,
      rating: 4.8,
      description: "1932 novel by English author Aldous Huxley.",
      genre: "science fiction",
      release_date: new Date("<1932-01-01>"),
    },
    {
      name: "Catch-22",
      image: "/images/p10.jpg",
      author: "Joseph Heller",
      price: 10.99,
      countInStock: 4,
      rating: 4.3,
      description: "1961 satirical war novel by American author Joseph Heller.",
      genre: "Satire",
      release_date: new Date("<1961-11-10>"),
    },
    {
      name: "The Grapes of Wrath",
      image: "/images/p11.jpg",
      author: "John Steinbeck",
      price: 9.99,
      countInStock: 16,
      rating: 4.7,
      description: "1939 realist fiction novel by author John Steinbeck.",
      genre: "fiction",
      release_date: new Date("<1939-04-14>"),
    },
    {
      name: "A Study of History",
      image: "/images/p12.jpg",
      author: "Arnold J. Toynbee",
      price: 12.49,
      countInStock: 3,
      rating: 4.1,
      description: "a 12-volume universal history by the British hostorian Arnold J. Toynbee, published from 1934-1961.",
      genre: "non-fiction",
      release_date: new Date("<1961-01-01>"),
    },
    {
      name: "1984",
      image: "/images/p13.jpg",
      author: "George Orwell",
      price: 9.49,
      countInStock: 16,
      rating: 4.8,
      description: "A dystopian social science fiction novel by English novelist George Orwell.",
      genre: "fiction",
      release_date: new Date("<1949-07-08>"),
    },
    {
      name: "Darkness at Noon",
      image: "/images/p14.jpg",
      author: "Arthur Koestler",
      price: 7.69,
      countInStock: 8,
      rating: 4,
      description: "A novel by Hungarian-born British novelist Arthur Koestler, first published in 1940.",
      genre: "science fiction",
      release_date: new Date("<1940-01-01>"),
    },
    {
      name: "Where the Red Fern Grows",
      image: "/images/p15.jpg",
      author: "Wilson Rawls",
      price: 6.99,
      countInStock: 7,
      rating: 4.6,
      description: "A 1961 children's novel by Wilson Rawls about a boy who buys two hunting dogs.",
      genre: "fiction",
      release_date: new Date("<1961-01-01>"),
    },
    {
      name: "Slaughterhouse-Five",
      image: "/images/p16.jpg",
      author: "Kurt Vonnegut",
      price: 8.19,
      countInStock: 5,
      rating: 4.5,
      description: "A science fiction infused anti-war novel by Kurt Vonnegut.",
      genre: "science fiction",
      release_date: new Date("<1969-03-31>"),
    },
    {
      name: "Animal Farm",
      image: "/images/p17.jpg",
      author: "George Orwell",
      price: 8.00,
      countInStock: 13,
      rating: 4.7,
      description: "An allegorical novella by George Orwell, first published in England in 1945.",
      genre: "political satire",
      release_date: new Date("<1945-08-17>"),
    },
    {
      name: "Invisible Man",
      image: "/images/p18.jpg",
      author: "Ralph Ellison",
      price: 9.00,
      countInStock: 4,
      rating: 4.5,
      description: "A novel addressing many of the social and intellectual issues faced by the African Americans in the early twentieth century",
      genre: "african-american literature",
      release_date: new Date("<1952-04-14>"),
    },
    {
      name: "Lord of the Flies",
      image: "/images/p19.jpg",
      author: "William Golding",
      price: 9.59,
      countInStock: 6,
      rating: 4.8,
      description: "A novel by Nobel Prize-winning British author William Golding.",
      genre: "fiction",
      release_date: new Date("<1954-09-17>"),
    },
    {
      name: "A Clockwork Orange",
      image: "/images/p20.jpg",
      author: "Anthony Burgess",
      price: 8.49,
      countInStock: 10,
      rating: 4.7,
      description: "a dystopian satirical black comedy novel by English writer Anthony Burgess.",
      genre: "science fiction",
      release_date: new Date("<1962-01-01>"),
    },
    {
      name: "The Golden Bowl",
      image: "/images/p21.jpg",
      author: "Henry James",
      price: 6.49,
      countInStock: 4,
      rating: 3.9,
      description: "A 1904 novel by Henry James.",
      genre: "fiction",
      release_date: new Date("<1904-11-10>"),
    },
  ],
};
export default data;
