import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Gaby',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
    },
  ],

  products: [
    {
      name: "And Then There Were None",
      image: "/images/p1.jpg",
      author: "Agatha Christie",
      price: 7.99,
      countInStock: 10,
      rating: 4.5,
      description: "by Agatha Christie",
      genre: "fiction",
      release_date: new Date("<1939-11-06>"),
    },
    {
      name: "Alice's Adventures in Wonderland",
      image: "/images/p2.jpg",
      author: "Lewis Carroll",
      price: 10.0,
      countInStock: 20,
      rating: 4.0,
      description: "by Lewis Carroll",
      genre: "fantasy",
      release_date: new Date("<1865-01-01>"),
    },
    {
      name: "Harry Potter and the Goblet of Fire",
      image: "/images/p3.jpg",
      author: "J.K. Rowling, Mary GrandPre (Illustrator)",
      price: 11.69,
      countInStock: 10,
      rating: 4.8,
      description: "by J.K. Rowling, Mary GrandPre (Illustrator)",
      genre: "fantasy",
      release_date: new Date("<2005-11-18>"),
    },
    {
      name: "Anne of Green Gables",
      image: "/images/p4.jpg",
      author: "L.M. Montgomery",
      price: 7.99,
      countInStock: 15,
      rating: 4.5,
      description: "by L.M. Montgomery",
      genre: "autobiography",
      release_date: new Date("<1908-06-01>"),
    },
    {
      name: "Bridge to Terabithia",
      image: "/images/p5.jpg",
      author: "Katherine Paterson, Donna Diamond (Illustrator)",
      price: 7.99,
      countInStock: 5,
      rating: 4.5,
      description: "by Katherine Paterson, Donna Diamond (Illustrator)",
      genre: "fantasy",
      release_date: new Date("<2007-02-16>"),
    },
    {
      name: "Harry Potter and the Sorcerer's Stone",
      image: "/images/p6.jpg",
      author: "J.K. Rowling, Mary GrandPre (Illustrator)",
      price: 8.99,
      countInStock: 12,
      rating: 4.5,
      description: "1997 novel by British author J.K. Rowling, Mary GrandPre (Illustrator)",
      genre: "fantasy",
      release_date: new Date("<1997-06-26>"),
    },
  ],
};
export default data;
